// DO NOT EDIT
// Generated by JFlex 1.8.2 http://jflex.de/
// source: scanner.jflex

import java_cup.runtime.*;

// See https://github.com/jflex-de/jflex/issues/222
@SuppressWarnings("FallThrough")
class Example implements java_cup.runtime.Scanner {

  /** This character denotes the end of file. */
  public static final int YYEOF = -1;

  /** Initial size of the lookahead buffer. */
  private static final int ZZ_BUFFERSIZE = 16384;

  // Lexical states.
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = {
     0, 0
  };

  /**
   * Top-level table for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_TOP = zzUnpackcmap_top();

  private static final String ZZ_CMAP_TOP_PACKED_0 =
    "\1\0\25\u0100\1\u0200\11\u0100\1\u0300\17\u0100\1\u0400\u10cf\u0100";

  private static int [] zzUnpackcmap_top() {
    int [] result = new int[4352];
    int offset = 0;
    offset = zzUnpackcmap_top(ZZ_CMAP_TOP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_top(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Second-level tables for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_BLOCKS = zzUnpackcmap_blocks();

  private static final String ZZ_CMAP_BLOCKS_PACKED_0 =
    "\11\0\5\1\22\0\1\1\1\2\3\0\1\3\1\4"+
    "\1\0\1\5\1\6\1\7\1\10\1\0\1\11\1\12"+
    "\1\13\12\14\1\15\1\16\1\17\1\20\1\21\2\0"+
    "\32\22\4\0\1\22\1\0\1\23\1\24\1\25\1\26"+
    "\1\27\1\30\1\31\1\32\1\33\1\22\1\34\1\35"+
    "\1\22\1\36\1\37\2\22\1\40\1\41\1\42\1\43"+
    "\1\22\1\44\3\22\1\45\1\46\1\47\7\0\1\1"+
    "\32\0\1\1\u01df\0\1\1\177\0\13\1\35\0\2\1"+
    "\5\0\1\1\57\0\1\1\240\0\1\1\377\0";

  private static int [] zzUnpackcmap_blocks() {
    int [] result = new int[1280];
    int offset = 0;
    offset = zzUnpackcmap_blocks(ZZ_CMAP_BLOCKS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_blocks(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /**
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\1\2\1\3\1\0\1\4\1\5\1\6"+
    "\1\7\1\10\1\11\1\12\1\13\1\14\1\15\1\16"+
    "\1\17\11\20\1\21\1\0\1\22\1\23\1\24\1\0"+
    "\1\25\1\26\1\27\4\20\1\30\2\20\1\31\4\20"+
    "\1\32\1\12\7\20\1\33\4\20\1\34\2\20\1\35"+
    "\3\20\1\36\4\20\1\37\1\20\1\40\1\41";

  private static int [] zzUnpackAction() {
    int [] result = new int[77];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\50\0\50\0\50\0\120\0\50\0\50\0\50"+
    "\0\170\0\240\0\50\0\310\0\50\0\50\0\360\0\u0118"+
    "\0\u0140\0\u0168\0\u0190\0\u01b8\0\u01e0\0\u0208\0\u0230\0\u0258"+
    "\0\u0280\0\u02a8\0\50\0\u02d0\0\50\0\50\0\50\0\u02f8"+
    "\0\50\0\50\0\50\0\u0320\0\u0348\0\u0370\0\u0398\0\u03c0"+
    "\0\u03e8\0\u0410\0\u0168\0\u0438\0\u0460\0\u0488\0\u04b0\0\50"+
    "\0\u02f8\0\u04d8\0\u0500\0\u0528\0\u0550\0\u0578\0\u05a0\0\u05c8"+
    "\0\u0168\0\u05f0\0\u0618\0\u0640\0\u0668\0\u0168\0\u0690\0\u06b8"+
    "\0\u0168\0\u06e0\0\u0708\0\u0730\0\u0168\0\u0758\0\u0780\0\u07a8"+
    "\0\u07d0\0\u0168\0\u07f8\0\u0168\0\u0168";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[77];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /**
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\0\1\2\1\3\1\4\1\5\1\6\1\7\1\10"+
    "\1\11\1\12\1\0\1\13\1\14\1\15\1\16\1\17"+
    "\1\20\1\21\2\22\1\23\1\24\1\25\1\26\1\27"+
    "\2\22\1\30\5\22\1\31\2\22\1\32\1\33\1\34"+
    "\1\35\54\0\1\36\53\0\1\37\50\0\1\37\50\0"+
    "\1\40\1\0\1\14\53\0\1\41\47\0\1\42\47\0"+
    "\1\43\43\0\1\22\5\0\23\22\17\0\1\22\5\0"+
    "\16\22\1\44\4\22\17\0\1\22\5\0\1\22\1\45"+
    "\6\22\1\46\12\22\17\0\1\22\5\0\5\22\1\47"+
    "\7\22\1\50\5\22\17\0\1\22\5\0\13\22\1\51"+
    "\7\22\17\0\1\22\5\0\13\22\1\52\7\22\17\0"+
    "\1\22\5\0\6\22\1\53\5\22\1\54\6\22\17\0"+
    "\1\22\5\0\20\22\1\55\1\22\1\56\17\0\1\22"+
    "\5\0\10\22\1\57\12\22\51\0\1\60\15\0\1\61"+
    "\47\0\1\22\5\0\5\22\1\62\15\22\17\0\1\22"+
    "\5\0\17\22\1\63\3\22\17\0\1\22\5\0\1\22"+
    "\1\64\21\22\17\0\1\22\5\0\6\22\1\65\14\22"+
    "\17\0\1\22\5\0\21\22\1\66\1\22\17\0\1\22"+
    "\5\0\17\22\1\67\3\22\17\0\1\22\5\0\15\22"+
    "\1\70\5\22\17\0\1\22\5\0\20\22\1\71\2\22"+
    "\17\0\1\22\5\0\16\22\1\72\4\22\17\0\1\22"+
    "\5\0\11\22\1\73\11\22\17\0\1\22\5\0\11\22"+
    "\1\74\11\22\17\0\1\22\5\0\1\22\1\75\21\22"+
    "\17\0\1\22\5\0\5\22\1\76\15\22\17\0\1\22"+
    "\5\0\16\22\1\71\4\22\17\0\1\22\5\0\1\22"+
    "\1\77\21\22\17\0\1\22\5\0\2\22\1\100\20\22"+
    "\17\0\1\22\5\0\5\22\1\101\15\22\17\0\1\22"+
    "\5\0\1\22\1\54\21\22\17\0\1\22\5\0\11\22"+
    "\1\102\11\22\17\0\1\22\5\0\20\22\1\103\2\22"+
    "\17\0\1\22\5\0\13\22\1\104\7\22\17\0\1\22"+
    "\5\0\12\22\1\105\10\22\17\0\1\22\5\0\21\22"+
    "\1\106\1\22\17\0\1\22\5\0\13\22\1\107\7\22"+
    "\17\0\1\22\5\0\14\22\1\110\6\22\17\0\1\22"+
    "\5\0\3\22\1\111\17\22\17\0\1\22\5\0\5\22"+
    "\1\112\15\22\17\0\1\22\5\0\13\22\1\113\7\22"+
    "\17\0\1\22\5\0\5\22\1\71\15\22\17\0\1\22"+
    "\5\0\7\22\1\71\13\22\17\0\1\22\5\0\10\22"+
    "\1\114\12\22\17\0\1\22\5\0\20\22\1\115\2\22"+
    "\3\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[2080];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** Error code for "Unknown internal scanner error". */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  /** Error code for "could not match input". */
  private static final int ZZ_NO_MATCH = 1;
  /** Error code for "pushback value was too large". */
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /**
   * Error messages for {@link #ZZ_UNKNOWN_ERROR}, {@link #ZZ_NO_MATCH}, and
   * {@link #ZZ_PUSHBACK_2BIG} respectively.
   */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state {@code aState}
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\3\11\1\0\3\11\2\1\1\11\1\1\2\11"+
    "\14\1\1\11\1\0\3\11\1\0\3\11\14\1\1\11"+
    "\35\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[77];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** Input device. */
  private java.io.Reader zzReader;

  /** Current state of the DFA. */
  private int zzState;

  /** Current lexical state. */
  private int zzLexicalState = YYINITIAL;

  /**
   * This buffer contains the current text to be matched and is the source of the {@link #yytext()}
   * string.
   */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** Text position at the last accepting state. */
  private int zzMarkedPos;

  /** Current text position in the buffer. */
  private int zzCurrentPos;

  /** Marks the beginning of the {@link #yytext()} string in the buffer. */
  private int zzStartRead;

  /** Marks the last character in the buffer, that has been read from input. */
  private int zzEndRead;

  /**
   * Whether the scanner is at the end of file.
   * @see #yyatEOF
   */
  private boolean zzAtEOF;

  /**
   * The number of occupied positions in {@link #zzBuffer} beyond {@link #zzEndRead}.
   *
   * <p>When a lead/high surrogate has been read from the input stream into the final
   * {@link #zzBuffer} position, this will have a value of 1; otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /** Number of newlines encountered up to the start of the matched text. */
  @SuppressWarnings("unused")
  private int yyline;

  /** Number of characters from the last newline up to the start of the matched text. */
  @SuppressWarnings("unused")
  private int yycolumn;

  /** Number of characters up to the start of the matched text. */
  @SuppressWarnings("unused")
  private long yychar;

  /** Whether the scanner is currently at the beginning of a line. */
  @SuppressWarnings("unused")
  private boolean zzAtBOL = true;

  /** Whether the user-EOF-code has already been executed. */
  private boolean zzEOFDone;


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  Example(java.io.Reader in) {
    this.zzReader = in;
  }

  /**
   * Translates raw input code points to DFA table row
   */
  private static int zzCMap(int input) {
    int offset = input & 255;
    return offset == input ? ZZ_CMAP_BLOCKS[offset] : ZZ_CMAP_BLOCKS[ZZ_CMAP_TOP[input >> 8] | offset];
  }

  /**
   * Refills the input buffer.
   *
   * @return {@code false} iff there was new input.
   * @exception java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead - zzStartRead);

      /* translate stored positions */
      zzEndRead -= zzStartRead;
      zzCurrentPos -= zzStartRead;
      zzMarkedPos -= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzBuffer.length * 2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      throw new java.io.IOException(
          "Reader returned 0 characters. See JFlex examples/zero-reader for a workaround.");
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
        if (numRead == requested) { // We requested too few chars to encode a full Unicode character
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        } else {                    // There is room in the buffer for at least one more char
          int c = zzReader.read();  // Expecting to read a paired low surrogate char
          if (c == -1) {
            return true;
          } else {
            zzBuffer[zzEndRead++] = (char)c;
          }
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }


  /**
   * Closes the input reader.
   *
   * @throws java.io.IOException if the reader could not be closed.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true; // indicate end of file
    zzEndRead = zzStartRead; // invalidate buffer

    if (zzReader != null) {
      zzReader.close();
    }
  }


  /**
   * Resets the scanner to read from a new input stream.
   *
   * <p>Does not close the old reader.
   *
   * <p>All internal variables are reset, the old input stream <b>cannot</b> be reused (internal
   * buffer is discarded and lost). Lexical state is set to {@code ZZ_INITIAL}.
   *
   * <p>Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader The new input stream.
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzEOFDone = false;
    yyResetPosition();
    zzLexicalState = YYINITIAL;
    if (zzBuffer.length > ZZ_BUFFERSIZE) {
      zzBuffer = new char[ZZ_BUFFERSIZE];
    }
  }

  /**
   * Resets the input position.
   */
  private final void yyResetPosition() {
      zzAtBOL  = true;
      zzAtEOF  = false;
      zzCurrentPos = 0;
      zzMarkedPos = 0;
      zzStartRead = 0;
      zzEndRead = 0;
      zzFinalHighSurrogate = 0;
      yyline = 0;
      yycolumn = 0;
      yychar = 0L;
  }


  /**
   * Returns whether the scanner has reached the end of the reader it reads from.
   *
   * @return whether the scanner has reached EOF.
   */
  public final boolean yyatEOF() {
    return zzAtEOF;
  }


  /**
   * Returns the current lexical state.
   *
   * @return the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state.
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   *
   * @return the matched text.
   */
  public final String yytext() {
    return new String(zzBuffer, zzStartRead, zzMarkedPos-zzStartRead);
  }


  /**
   * Returns the character at the given position from the matched text.
   *
   * <p>It is equivalent to {@code yytext().charAt(pos)}, but faster.
   *
   * @param position the position of the character to fetch. A value from 0 to {@code yylength()-1}.
   *
   * @return the character at {@code position}.
   */
  public final char yycharat(int position) {
    return zzBuffer[zzStartRead + position];
  }


  /**
   * How many characters were matched.
   *
   * @return the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occurred while scanning.
   *
   * <p>In a well-formed scanner (no or only correct usage of {@code yypushback(int)} and a
   * match-all fallback rule) this method will only be called with things that
   * "Can't Possibly Happen".
   *
   * <p>If this method is called, something is seriously wrong (e.g. a JFlex bug producing a faulty
   * scanner etc.).
   *
   * <p>Usual syntax/scanner level error handling should be done in error fallback rules.
   *
   * @param errorCode the code of the error message to display.
   */
  private static void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    } catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  }


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * <p>They will be read again by then next call of the scanning method.
   *
   * @param number the number of characters to be read again. This number must not be greater than
   *     {@link #yylength()}.
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
    
  yyclose();    }
  }




  /**
   * Resumes scanning until the next regular expression is matched, the end of input is encountered
   * or an I/O-Error occurs.
   *
   * @return the next token.
   * @exception java.io.IOException if any I/O-Error occurs.
   */
  @Override  public java_cup.runtime.Symbol next_token() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char[] zzBufferL = zzBuffer;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;

      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {

          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMap(zzInput) ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
            zzDoEOF();
          { return new java_cup.runtime.Symbol(sym.EOF); }
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1:
            { 
            }
            // fall through
          case 34: break;
          case 2:
            { System.out.println("<" + yytext() +", NOT>");return new Symbol(sym.NOT);
            }
            // fall through
          case 35: break;
          case 3:
            { System.out.println("<" + yytext() +", MOD >");return new Symbol(sym.MOD);
            }
            // fall through
          case 36: break;
          case 4:
            { System.out.println("<" + yytext() +", LP>");return new Symbol(sym.LP);
            }
            // fall through
          case 37: break;
          case 5:
            { System.out.println("<" + yytext() +", RP>");return new Symbol(sym.RP);
            }
            // fall through
          case 38: break;
          case 6:
            { System.out.println("<" + yytext() +",MUL >");return new Symbol(sym.MUL);
            }
            // fall through
          case 39: break;
          case 7:
            { System.out.println("<" + yytext() +", PLUS>");return new Symbol(sym.PLUS);
            }
            // fall through
          case 40: break;
          case 8:
            { System.out.println("<" + yytext() +", MINUS>");return new Symbol(sym.MINUS);
            }
            // fall through
          case 41: break;
          case 9:
            { System.out.println("<" + yytext() +", DIV >");return new Symbol(sym.DIV);
            }
            // fall through
          case 42: break;
          case 10:
            { System.out.println("<" + yytext() +", NUMB>");return new Symbol(sym.NUMB);
            }
            // fall through
          case 43: break;
          case 11:
            { System.out.println("<" + yytext() +", COLON>");return new Symbol(sym.COLON);
            }
            // fall through
          case 44: break;
          case 12:
            { System.out.println("<" + yytext() +", TER>");return new Symbol(sym.TER);
            }
            // fall through
          case 45: break;
          case 13:
            { System.out.println("<" + yytext() +", LT>");return new Symbol(sym.LT);
            }
            // fall through
          case 46: break;
          case 14:
            { System.out.println("<" + yytext() +", ASS>");return new Symbol(sym.ASS);
            }
            // fall through
          case 47: break;
          case 15:
            { System.out.println("<" + yytext() +", GT>");return new Symbol(sym.GT);
            }
            // fall through
          case 48: break;
          case 16:
            { System.out.println("<" + yytext() +", ID>");return new Symbol(sym.ID);
            }
            // fall through
          case 49: break;
          case 17:
            { System.out.println("<" + yytext() +", LP>");return new Symbol(sym.LCB);
            }
            // fall through
          case 50: break;
          case 18:
            { System.out.println("<" + yytext() +", RP>");return new Symbol(sym.RCB);
            }
            // fall through
          case 51: break;
          case 19:
            { System.out.println("<" + yytext() +", AND>");return new Symbol(sym.AND);
            }
            // fall through
          case 52: break;
          case 20:
            { System.out.println("<" + yytext() +", UNARY>");return new Symbol(sym.UNARY);
            }
            // fall through
          case 53: break;
          case 21:
            { System.out.println("<" + yytext() +", LTE>");return new Symbol(sym.LTE);
            }
            // fall through
          case 54: break;
          case 22:
            { System.out.println("<" + yytext() +", EQ>");return new Symbol(sym.EQ);
            }
            // fall through
          case 55: break;
          case 23:
            { System.out.println("<" + yytext() +", GTE>");return new Symbol(sym.GTE);
            }
            // fall through
          case 56: break;
          case 24:
            { System.out.println("<" + yytext() +", DO>");return new Symbol(sym.DO);
            }
            // fall through
          case 57: break;
          case 25:
            { System.out.println("<" + yytext() +", IF>");return new Symbol(sym.IF);
            }
            // fall through
          case 58: break;
          case 26:
            { System.out.println("<" + yytext() +", OR>");return new Symbol(sym.OR);
            }
            // fall through
          case 59: break;
          case 27:
            { System.out.println("<" + yytext() +", DTYPE>");return new Symbol(sym.DTYPE);
            }
            // fall through
          case 60: break;
          case 28:
            { System.out.println("<" + yytext() +", CASE>");return new Symbol(sym.CASE);
            }
            // fall through
          case 61: break;
          case 29:
            { System.out.println("<" + yytext() +", ELSE>");return new Symbol(sym.ELSE);
            }
            // fall through
          case 62: break;
          case 30:
            { System.out.println("<" + yytext() +", BREAK>");return new Symbol(sym.BREAK);
            }
            // fall through
          case 63: break;
          case 31:
            { System.out.println("<" + yytext() +", WHILE>");return new Symbol(sym.WHILE);
            }
            // fall through
          case 64: break;
          case 32:
            { System.out.println("<" + yytext() +", SWCH>");return new Symbol(sym.SWCH);
            }
            // fall through
          case 65: break;
          case 33:
            { System.out.println("<" + yytext() +", DEFAULT>");return new Symbol(sym.DEFAULT);
            }
            // fall through
          case 66: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
