
//----------------------------------------------------
// The following code was generated by CUP v0.11b beta 20140226
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int UNARY = 23;
  public static final int MOD = 7;
  public static final int AND = 14;
  public static final int LT = 20;
  public static final int ELSE = 26;
  public static final int PLUS = 3;
  public static final int OR = 13;
  public static final int LTE = 22;
  public static final int LP = 8;
  public static final int WHILE = 32;
  public static final int RP = 9;
  public static final int TER = 2;
  public static final int NOT = 15;
  public static final int IF = 25;
  public static final int COLON = 29;
  public static final int GT = 19;
  public static final int GTE = 21;
  public static final int ID = 16;
  public static final int ASS = 17;
  public static final int NUMB = 12;
  public static final int LCB = 10;
  public static final int DO = 33;
  public static final int DTYPE = 24;
  public static final int EOF = 0;
  public static final int BREAK = 30;
  public static final int DIV = 6;
  public static final int MINUS = 4;
  public static final int CASE = 28;
  public static final int error = 1;
  public static final int SWCH = 27;
  public static final int EQ = 18;
  public static final int RCB = 11;
  public static final int DEFAULT = 31;
  public static final int MUL = 5;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "TER",
  "PLUS",
  "MINUS",
  "MUL",
  "DIV",
  "MOD",
  "LP",
  "RP",
  "LCB",
  "RCB",
  "NUMB",
  "OR",
  "AND",
  "NOT",
  "ID",
  "ASS",
  "EQ",
  "GT",
  "LT",
  "GTE",
  "LTE",
  "UNARY",
  "DTYPE",
  "IF",
  "ELSE",
  "SWCH",
  "CASE",
  "COLON",
  "BREAK",
  "DEFAULT",
  "WHILE",
  "DO"
  };
public String[] TT;
	public sym(){
		TT = new String[100];
		TT[23]=new String("UNARY");
		TT[7]=new String("MOD");
		TT[14]=new String("AND");
		TT[20]=new String("LT");
		TT[26]=new String("ELSE");
		TT[3]=new String("PLUS");
		TT[13]=new String("OR");
		TT[22]=new String("LTE");
		TT[8]=new String("LP");
		TT[32]=new String("WHILE");
		TT[9]=new String("RP");
		TT[2]=new String("TER");
		TT[15]=new String("NOT");
		TT[25]=new String("IF");
		TT[29]=new String("COLON");
		TT[19]=new String("GT");
		TT[21]=new String("GTE");
		TT[16]=new String("ID");
		TT[17]=new String("ASS");
		TT[12]=new String("NUMB");
		TT[10]=new String("LCB");
		TT[33]=new String("DO");
		TT[24]=new String("DTYPE");
		TT[0]=new String("EOF");
		TT[30]=new String("BREAK");
		TT[6]=new String("DIV");
		TT[4]=new String("MINUS");
		TT[28]=new String("CASE");
		TT[1]=new String("error");
		TT[27]=new String("SWCH");
		TT[18]=new String("EQ");
		TT[11]=new String("RCB");
		TT[31]=new String("DEFAULT");
		TT[5]=new String("MUL");
	}
public String getTT(int i){return TT[i];}
}

